language: node_js
cache: 
  directories:
    - node_modules
notifications:
  email: false
node_js: 
  - '14.17.1'
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: main
  on:
    branch: master